[project]
name = "docai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.0",
    "python-calamine>=0.3.1",
    "tabulate>=0.9.0",
]
