[project]
name = "docai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.0",
    "python-calamine>=0.3.1",
    "python-docx>=1.1.2",
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "httpx>=0.27.2",
    "ipykernel>=6.29.5",
    "pre-commit>=4.0.1",
    "pytest>=8.3.3",
    "rich>=13.9.4",
]
