[project]
name = "docai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastexcel>=0.12.0",
    "tabulate>=0.9.0",
]
